# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z95LpwjPyjcDFJ9TLCzE2gKOmIdrEq9O
"""

list = []
for i in range(1000000000):
  list.append(i)
print(list)

